graph LR
  nodeos-usersfs === root{root}
  nodeos-usersfs === nodeos{nodeos}

  root --- bin-getty
  root === logon
  root --- forever
  root --- forever-monitor

  bin-getty --- src-termios
  bin-getty --- src-unistd

  logon --- posix
  logon --- kexec
  logon --- prompt

  src-termios --- nan
  src-unistd --- nan

  posix --- nan
