graph BT
  subgraph initramfs
    / === ibin[bin]
    / --- DEV((dev))
    / === ilib[lib]
    / --- proc((proc))
    / === tmp
    / === usr
  end

  subgraph usersfs
    tmp === workdirs(.workdirs)
    tmp === nodeos

    nodeos --- nbin[bin]
    nodeos === netc[etc]
    nodeos --- nlib[lib]
    nodeos --- ntmp((tmp))
  end
